In [2]:
import pickle
import cPickle
from matplotlib import pyplot as plt
data_link = "C:/Users/TobyCurtis/Desktop/speed measure/2016-ITS-BrnoCompSpeed/dataset/session0_center/gt_data.pkl"
# image = cv2.imread(data_link)
# plt.imshow(image)
with open(data_link, 'rb') as fid:
    gtData = cPickle.load(fid)

In [3]:
for key, value in gtData.iteritems() :
    print(key)

distanceMeasurement
measurementLines
cars
fps
invalidLanes
laneDivLines


In [80]:
print(gtData['measurementLines'])

[array([ 1.70533171e-02,  9.99854582e-01, -8.80561588e+02]), array([ 1.73467122e-04,  9.99999985e-01, -7.30587401e+02]), array([-4.55848494e-03,  9.99989610e-01, -6.33072297e+02])]


In [81]:
print(gtData['laneDivLines'])

[array([ -0.92226493,   0.38655841, 130.89136422]), array([-0.78325241,  0.62170384, 97.52101372]), array([-0.65281474,  0.7575176 , 71.40300615]), array([-0.5561045 ,  0.83111238, 51.65539177])]


In [4]:
for i in gtData['cars']:
    print(i)

{'laneIndex': set([0]), 'carId': 0, 'timeIntersectionLastShifted': -28.654716152154723, 'valid': True, 'intersections': [{'measurementLineId': 2, 'videoTime': 1.821365438984027}, {'measurementLineId': 1, 'videoTime': 2.1501775935128147}, {'measurementLineId': 0, 'videoTime': 2.485283847845277}], 'speed': 75.91294250515793}
{'laneIndex': set([1]), 'carId': 1, 'timeIntersectionLastShifted': -27.613092175430086, 'valid': True, 'intersections': [{'measurementLineId': 2, 'videoTime': 2.9296013264572163}, {'measurementLineId': 1, 'videoTime': 3.224366273702196}, {'measurementLineId': 0, 'videoTime': 3.526907824569914}], 'speed': 84.37879072008805}
{'laneIndex': set([2]), 'carId': 2, 'timeIntersectionLastShifted': -26.803317346642228, 'valid': True, 'intersections': [{'measurementLineId': 2, 'videoTime': 3.776441804778364}, {'measurementLineId': 1, 'videoTime': 4.054460981040495}, {'measurementLineId': 0, 'videoTime': 4.336682653357772}], 'speed': 89.96130883315331}
{'laneIndex': set([1]), 'c

In [5]:
SPLIT_TRAIN_SESSIONS = {}
SPLIT_TRAIN_SESSIONS["A"] = {"session0"}
SPLIT_TRAIN_SESSIONS["B"] = SPLIT_TRAIN_SESSIONS["A"] | {"session1", "session2"}
a = [1,2,3]
print(set(a))

set([1, 2, 3])


In [6]:
# DATASET_BASE_PATH = TRANS_PATH("../dataset/")
# RESULTS_DIR = TRANS_PATH("../results/")

DATASET_SESSIONS = {
    "session0": {
        "recordings": {        
            "left": {"fps": 50.0},
            "center": {"fps": 25.0},
            "right": {"fps": 50.0}
        }
        
    },
    "session1": {
        "recordings": {        
            "left": {"fps": 50.0},
            "center": {"fps": 50.0},
            "right": {"fps": 50.0}
        }
    },
    "session2": {
        "recordings": {        
            "left": {"fps": 50.0},
            "center": {"fps": 50.0},
            "right": {"fps": 50.0}
        }
    },
    "session3": {
        "recordings": {        
            "left": {"fps": 50.0},
            "center": {"fps": 50.0},
            "right": {"fps": 50.0}
        }
    },
    "session4": {
        "recordings": {        
            "left": {"fps": 50.0},
            "center": {"fps": 50.0},
            "right": {"fps": 50.0}
        }
    },
    "session5": {
        "recordings": {        
            "left": {"fps": 50.0},
            "center": {"fps": 50.0},
            "right": {"fps": 50.0}
        }
    },
    "session6": {
        "recordings": {        
            "left": {"fps": 50.0},
            "center": {"fps": 50.0},
            "right": {"fps": 50.0}
        },
        "invalidLanes": set([2])
        
    }
    
}





ALL_SESSIONS = set(DATASET_SESSIONS.keys())

ALL_VIDEOS = []
for _sId in sorted(DATASET_SESSIONS):
    for _rId in ("left", "center", "right"):
        ALL_VIDEOS.append((_sId, _rId))

SPLIT_TRAIN_SESSIONS = {}
SPLIT_TRAIN_SESSIONS["A"] = {"session0"}
SPLIT_TRAIN_SESSIONS["B"] = SPLIT_TRAIN_SESSIONS["A"] | {"session1", "session2"}
SPLIT_TRAIN_SESSIONS["C"] = SPLIT_TRAIN_SESSIONS["B"] | {"session3"}

SPLIT_TEST_SESSIONS = dict(map(lambda i: (i[0], ALL_SESSIONS-i[1]), SPLIT_TRAIN_SESSIONS.iteritems()))

SPLIT_TRAIN_VIDEOS = dict(map(lambda i: (i[0], filter(lambda j: j[0] in i[1], ALL_VIDEOS)), SPLIT_TRAIN_SESSIONS.iteritems()))
SPLIT_TEST_VIDEOS = dict(map(lambda i: (i[0], filter(lambda j: j[0] in i[1], ALL_VIDEOS)), SPLIT_TEST_SESSIONS.iteritems()))

print SPLIT_TRAIN_SESSIONS
print ""
print SPLIT_TEST_SESSIONS
print ""
print SPLIT_TRAIN_VIDEOS
print ""
print SPLIT_TEST_VIDEOS

{'A': set(['session0']), 'C': set(['session0', 'session1', 'session2', 'session3']), 'B': set(['session0', 'session1', 'session2'])}

{'A': set(['session4', 'session5', 'session6', 'session1', 'session2', 'session3']), 'C': set(['session4', 'session5', 'session6']), 'B': set(['session4', 'session5', 'session6', 'session3'])}

{'A': [('session0', 'left'), ('session0', 'center'), ('session0', 'right')], 'C': [('session0', 'left'), ('session0', 'center'), ('session0', 'right'), ('session1', 'left'), ('session1', 'center'), ('session1', 'right'), ('session2', 'left'), ('session2', 'center'), ('session2', 'right'), ('session3', 'left'), ('session3', 'center'), ('session3', 'right')], 'B': [('session0', 'left'), ('session0', 'center'), ('session0', 'right'), ('session1', 'left'), ('session1', 'center'), ('session1', 'right'), ('session2', 'left'), ('session2', 'center'), ('session2', 'right')]}

{'A': [('session1', 'left'), ('session1', 'center'), ('session1', 'right'), ('session2', 'left'),

In [4]:
from __future__ import division
from __future__ import print_function
import numpy as np
import os
import matplotlib.pyplot as plt
import cPickle
def pointToLineDistance(p, l):
    return abs(np.dot(l,p/p[2]))/np.linalg.norm(l[0:2])

def pointToLineProjection(l, p):
    p = p/p[-1]
    c = p[0]*l[1] - p[1]*l[0]
    perpendicularLine = np.array([-l[1], l[0], c])
    intersection = np.cross(l, perpendicularLine)
    return intersection/intersection[-1]

p = np.array([1,2,1])
l = np.array([1,-1,0])
# pointToLineDistance(p,l)
pointToLineProjection(p,l)

D:\anaconda\envs\Python2.7\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()
D:\anaconda\envs\Python2.7\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()


array([ inf, -inf,   1.])

In [5]:
import numpy as np
def isPointBetweenLines(p, l1, l2):
    return np.dot(p,l1)*np.dot(p,l2)*np.dot(l1[0:2],l2[0:2]) <= 0
def getLaneForPoint(p, lines):
    for i in xrange(len(lines)-1):
        print(i)
        if isPointBetweenLines(p, lines[i], lines[i+1]):
            return i
    return None
p = np.array([1,2,1])
l1 = np.array([1,2,3])
l2 = np.array([2,2,3])
l3 = np.array([3,2,3])
l = [l1,l2,l3]
print(getLaneForPoint(p,l))

0
1
None


In [6]:
from __future__ import division
from __future__ import print_function
import numpy as np
import math

def getFocal(vp1, vp2, pp):
    return math.sqrt(- np.dot(vp1[0:2]-pp[0:2], vp2[0:2]-pp[0:2]))

def isPointBetweenLines(p, l1, l2):
    return np.dot(p,l1)*np.dot(p,l2)*np.dot(l1[0:2],l2[0:2]) <= 0

def computeCameraCalibration(_vp1, _vp2, _pp):
    vp1 = np.concatenate((_vp1, [1]))    
    vp2 = np.concatenate((_vp2, [1]))    
    pp = np.concatenate((_pp, [1]))    
    focal = getFocal(vp1, vp2, pp)
    vp1W = np.concatenate((_vp1, [focal]))    
    vp2W = np.concatenate((_vp2, [focal]))    
    ppW = np.concatenate((_pp, [0])) 
    vp3W = np.cross(vp1W-ppW, vp2W-ppW)
    vp3 = np.concatenate((vp3W[0:2]/vp3W[2]*focal + ppW[0:2], [1]))
    vp3Direction = np.concatenate((vp3[0:2], [focal]))-ppW
    roadPlane = np.concatenate((vp3Direction/np.linalg.norm(vp3Direction), [10]))
    return vp1, vp2, vp3, pp, roadPlane, focal

def getWorldCoordinagesOnRoadPlane(p, focal, roadPlane, pp):
    p = p/p[2]
    pp = pp/pp[2]
    ppW = np.concatenate((pp[0:2], [0]))
    pW = np.concatenate((p[0:2], [focal]))
    dirVec = pW - ppW
    t = -np.dot(roadPlane, np.concatenate((ppW, [1])))/np.dot(roadPlane[0:3], dirVec)
    return ppW + t*dirVec

vp1 = np.array([144.737, 34.7794])
vp2 = np.array([12183.582175112755, 615.451021479187])
pp = np.array([960, 540])
computeCameraCalibration(vp1,vp2,pp)


(array([144.737 ,  34.7794,   1.    ]),
 array([1.21835822e+04, 6.15451021e+02, 1.00000000e+00]),
 array([8.76075254e+00, 2.02616837e+04, 1.00000000e+00]),
 array([960, 540,   1]),
 array([-0.04761926,  0.98727215,  0.15174356, 10.        ]),
 3031.219339667006)

In [7]:
import platform
TRANS_PATH = lambda p: p
TRANS_PATH(2)

2

In [67]:
from __future__ import division

import matplotlib
matplotlib.rcParams['text.latex.unicode'] = True
font = {'size'   : 13}
matplotlib.rc('font', **font)

import scipy.ndimage
import scipy.stats
import scipy.optimize
import matplotlib.pyplot as plt
import json
import scipy.stats
from tabulate import tabulate
import operator
import itertools
import sys
import argparse
from matplotlib.ticker import MultipleLocator

def getPathForRecording(session, recording):
    return os.path.join('./dataset/', "%s_%s"%(session, recording))

def getCarTimeAndSpatialIntersection(line, posX, posY, frames, around=6):
    points = map(lambda x,y,f: (np.array([x,y, 1]),f), posX, posY, frames)
    points.sort(key=lambda i: pointToLineDistance(i[0], line))
    getItems = lambda getter: map(getter, points[:min(around,len(points))])
    spatialLineSlope, spatialLineIntercept = scipy.stats.linregress(getItems(lambda i: i[0][0]),
                                                                    getItems(lambda i: i[0][1]))[:2]
    spatialLine = np.array([spatialLineSlope, -1, spatialLineIntercept])
    spatialIntersection = np.cross(spatialLine, line)
    spatialIntersection = spatialIntersection/spatialIntersection[-1]

    frameNumbers = getItems(lambda i: i[1])
    normalizationPoint = np.cross(spatialLine, [0,1,0])
    normalizationPoint = normalizationPoint/normalizationPoint[-1]
    pointsProjected = map(lambda p: pointToLineProjection(spatialLine, p[0]), points[:min(around,len(points))])
    pointsDists = map(lambda p: np.linalg.norm(normalizationPoint-p), pointsProjected)
    temporalLineSlope, temporalLineIntercept = scipy.stats.linregress(pointsDists,frameNumbers)[:2]
    temporalIntersection = temporalLineSlope * np.linalg.norm(spatialIntersection-normalizationPoint) + temporalLineIntercept

    return spatialIntersection, temporalIntersection, spatialLine

def getLaneForPoint(p, lines):
    for i in xrange(len(lines)-1):
        if isPointBetweenLines(p, lines[i], lines[i+1]):
            return i
    return None

def pointToLineProjection(l, p):
    p = p/p[-1]
    c = p[0]*l[1] - p[1]*l[0]
    perpendicularLine = np.array([-l[1], l[0], c])
    intersection = np.cross(l, perpendicularLine)
    return intersection/intersection[-1]
        
def pointToLineDistance(p, l):
    return abs(np.dot(l,p/p[2]))/np.linalg.norm(l[0:2])

def calculateSpeeds(sessionId, recordingId, data, gtData, system):
    '''
    Okay, now we will find the meaning of each line of code. I'm sure this guy is a student. A clever student
    '''    
    # this line, of course, no need to explain
#     vp1, vp2, vp3, pp, roadPlane, focal = computeCameraCalibration(data["camera_calibration"]["vp1"],
#                                                             data["camera_calibration"]["vp2"],
#                                                             data["camera_calibration"]["pp"])
    ''''''
    vp1 = np.array([174.5455,53.7662])
    vp2 = np.array([1505.3,96.9231])
    pp = np.array([960,540])
    vp1, vp2, vp3, pp, roadPlane, focal = computeCameraCalibration(vp1,
                                                            vp2,
                                                            pp)
#     vp3 = np.array([945.0162,1002,1])
    focal = 461.3994
    roadPlane = np.array([-0.0229, 0.7074, 0.7064, 10])
    ''''''
    # ah, lambda, remember it, my friend? 1 way in, 1 value out, impress. This line take the path of gtData
    pTran = lambda p: os.path.join(getPathForRecording(sessionId, recordingId), p)
    lines = gtData["measurementLines"]
    laneDivLines = gtData["laneDivLines"]
    fps = gtData["fps"]
    errors = 0
    for car in data["cars"]:
        intersectionData = map(lambda l: getCarTimeAndSpatialIntersection(l, car["posX"], car["posY"], car["frames"]), lines)
        startSpatial, startFrame, startLineSpatial = intersectionData[-1]
        endSpatial, endFrame, endLineSpatial = intersectionData[0]
        # test on poorly approximated intersections
        testMat = np.concatenate((endSpatial, startSpatial,
                                  [startFrame, endFrame]))
#         print(startSpatial, endSpatial)
        print(testMat)
        print(testMat.shape)
        break
        if not (np.any(np.isnan(testMat)) or \
                np.any(np.isinf(testMat)) or \
                getLaneForPoint(endSpatial, laneDivLines) is None or \
                getLaneForPoint(startSpatial, laneDivLines) is None):

            elapsedTime = abs(endFrame-startFrame)/fps
            projector = lambda p: getWorldCoordinagesOnRoadPlane(p, focal, roadPlane, pp)
            passedDistance = data["camera_calibration"]["scale"]*np.linalg.norm(projector(startSpatial)-projector(endSpatial))
            car["speed"] = passedDistance/elapsedTime * 3.6
            car["laneIndex"] = getLaneForPoint(endSpatial, laneDivLines)
            car["timeIntersectionLast"] = endFrame/fps

            car["timeIntersectionFirst"] = startFrame/fps
            car["spatialIntersectionFirst"] = startSpatial
            car["spatialIntersectionLast"] = endSpatial
            points = map(lambda x,y: np.array([x,y,1]), car["posX"], car["posY"])
            points = map(projector, points)
            frames = car["frames"]
            perFrameSpeeds = []
            pointsOffset = 10
            '''
            Toby
            '''
            count = 0
            for i in xrange(len(points)-pointsOffset):
                passedDistance = data["camera_calibration"]["scale"]*np.linalg.norm(points[i]-points[i+pointsOffset])
                elapsedTime = abs(frames[i]-frames[i+pointsOffset])/fps
                '''
                Toby
                '''
#                 print('At frame: {} with ID: {} is {}'.format(car['frames'][count],car['ID'],passedDistance/elapsedTime * 3.6))
                perFrameSpeeds.append(passedDistance/elapsedTime * 3.6)
                count+=1

            car["medianSpeed"] = np.median(perFrameSpeeds)
#             print(str(car['ID']) + ': ' + str(car["medianSpeed"]))
#             break

#         else:
#             errors += 1
#             if SHOW_ERRORS:
#                 img = scipy.misc.imread(pTran("screen.png"))
#                 scale = float(17.5)/WIDTH
#                 plt.figure(figsize = (img.shape[1]*scale, img.shape[0]*scale))
#                 plt.imshow(img)
                
#                 for l in lines:
#                     drawLinePyplot(l, color="yellow", ls="--", linewidth=2)
#                 drawLinePyplot(startLineSpatial,  color = "red", linewidth=2, label="approximation to first line")
#                 drawLinePyplot(endLineSpatial,  color = "blue", linewidth=2, label="approximation to last line")
#                 plt.plot(car["posX"], car["posY"], "o", color="black",markersize="4",label="trajectory")
#                 plt.legend()
#                 plt.title("ERROR approximating car: %s %s %s %d"%(system, sessionId, recordingId, car["id"]))
#                 plt.show()

    return data

In [77]:
import numpy as np
p1 = np.array([True, False, True])
# -1 or 0 or 5
# True or False
print(np.all(p1))

False


In [68]:
from __future__ import division
from __future__ import print_function
import json

sessionId = 'session0'
recordingId = 'center'
gD = gtData
system = 'dubska_optimal_calib'
# data = json.load(open('C:/Users/TobyCurtis/Desktop/BrnoCompSpeed/code/results/session0_center/system_dubska_optimal_calib.json'))
# data = json.load(open('C:/Users/ADMINS/Desktop/result.json'))
data_lap = json.load(open('C:/Users/TobyCurtis/Desktop/result.json'))

temp = calculateSpeeds(sessionId, recordingId, data_lap, gD, system)

[743.90779438 868.00171557   1.         506.19398274 635.38637616
   1.         204.28772947 225.12037444]
(8L,)


In [47]:
from __future__ import division
from __future__ import print_function
import json

sessionId = 'session0'
recordingId = 'center'
gD = gtData
system = 'dubska_optimal_calib'
# data = json.load(open('C:/Users/TobyCurtis/Desktop/BrnoCompSpeed/code/results/session0_center/system_dubska_optimal_calib.json'))
# data = json.load(open('C:/Users/ADMINS/Desktop/result.json'))
data_lap = json.load(open('C:/Users/TobyCurtis/Desktop/result.json'))

temp = calculateSpeeds(sessionId, recordingId, data, gD, system)

At frame: 31 with ID: 0 is 76.7569927402
At frame: 32 with ID: 0 is 76.7161627862
At frame: 33 with ID: 0 is 76.9769727313
At frame: 34 with ID: 0 is 77.2689131153
At frame: 35 with ID: 0 is 76.6171322664
At frame: 36 with ID: 0 is 76.5700917993
At frame: 37 with ID: 0 is 76.5784074246
At frame: 38 with ID: 0 is 77.0753584861
At frame: 39 with ID: 0 is 76.8246258623
At frame: 40 with ID: 0 is 77.6023115717
At frame: 41 with ID: 0 is 77.1861501193
At frame: 42 with ID: 0 is 77.0445875032
At frame: 43 with ID: 0 is 76.8185351467
At frame: 44 with ID: 0 is 77.0350055189
At frame: 45 with ID: 0 is 77.0657770224
At frame: 46 with ID: 0 is 76.8221611118
At frame: 47 with ID: 0 is 76.8943543951
At frame: 48 with ID: 0 is 76.668371226
At frame: 49 with ID: 0 is 76.5830704756
At frame: 50 with ID: 0 is 76.3399976945
At frame: 51 with ID: 0 is 76.4254910014
At frame: 52 with ID: 0 is 76.7406400282
At frame: 53 with ID: 0 is 76.6699203207
At frame: 54 with ID: 0 is 76.5929615718
At frame: 55 with

In [52]:
from __future__ import division
from __future__ import print_function
import json

sessionId = 'session0'
recordingId = 'center'
gD = gtData
system = 'dubska_optimal_calib'
# data = json.load(open('C:/Users/TobyCurtis/Desktop/BrnoCompSpeed/code/results/session0_center/system_dubska_optimal_calib.json'))
# data = json.load(open('C:/Users/ADMINS/Desktop/result.json'))
data_lap = json.load(open('C:/Users/TobyCurtis/Desktop/result.json'))

temp = calculateSpeeds(sessionId, recordingId, data_lap, gD, system)

At frame: 0.0 with ID: 281 is 31.8637357856
At frame: 1.0 with ID: 281 is 37.2999874063
At frame: 2.0 with ID: 281 is 41.632226764
At frame: 3.0 with ID: 281 is 40.1022017559
At frame: 4.0 with ID: 281 is 38.894373339
At frame: 5.0 with ID: 281 is 35.4958914847
At frame: 6.0 with ID: 281 is 32.3580352931
At frame: 7.0 with ID: 281 is 33.0762138473
At frame: 8.0 with ID: 281 is 30.970693375
At frame: 9.0 with ID: 281 is 28.6176458657
At frame: 10.0 with ID: 281 is 26.7675413965
At frame: 11.0 with ID: 281 is 33.6967152424
At frame: 12.0 with ID: 281 is 32.2551347144
At frame: 13.0 with ID: 281 is 31.4277168002
At frame: 14.0 with ID: 281 is 32.2570568469
At frame: 15.0 with ID: 281 is 35.1636511718
At frame: 16.0 with ID: 281 is 36.7836249373
At frame: 17.0 with ID: 281 is 36.5715018675
At frame: 18.0 with ID: 281 is 36.7859231566
At frame: 19.0 with ID: 281 is 38.6387920037
At frame: 20.0 with ID: 281 is 39.8638346901
At frame: 21.0 with ID: 281 is 27.5640681411
At frame: 22.0 with ID:

In [53]:
from __future__ import division
from __future__ import print_function
import json

sessionId = 'session0'
recordingId = 'center'
gD = gtData
system = 'dubska_optimal_calib'
# data = json.load(open('C:/Users/TobyCurtis/Desktop/BrnoCompSpeed/code/results/session0_center/system_dubska_optimal_calib.json'))
# data = json.load(open('C:/Users/ADMINS/Desktop/result.json'))
data_lap = json.load(open('C:/Users/TobyCurtis/Desktop/result.json'))

temp = calculateSpeeds(sessionId, recordingId, data_lap, gD, system)

At frame: 0.0 with ID: 281 is 31.8637357856
At frame: 1.0 with ID: 281 is 37.2999874063
At frame: 2.0 with ID: 281 is 41.632226764
At frame: 3.0 with ID: 281 is 40.1022017559
At frame: 4.0 with ID: 281 is 38.894373339
At frame: 5.0 with ID: 281 is 35.4958914847
At frame: 6.0 with ID: 281 is 32.3580352931
At frame: 7.0 with ID: 281 is 33.0762138473
At frame: 8.0 with ID: 281 is 30.970693375
At frame: 9.0 with ID: 281 is 28.6176458657
At frame: 10.0 with ID: 281 is 26.7675413965
At frame: 11.0 with ID: 281 is 33.6967152424
At frame: 12.0 with ID: 281 is 32.2551347144
At frame: 13.0 with ID: 281 is 31.4277168002
At frame: 14.0 with ID: 281 is 32.2570568469
At frame: 15.0 with ID: 281 is 35.1636511718
At frame: 16.0 with ID: 281 is 36.7836249373
At frame: 17.0 with ID: 281 is 36.5715018675
At frame: 18.0 with ID: 281 is 36.7859231566
At frame: 19.0 with ID: 281 is 38.6387920037
At frame: 20.0 with ID: 281 is 39.8638346901
At frame: 21.0 with ID: 281 is 27.5640681411
At frame: 22.0 with ID:

In [38]:
print(data['cars'][3])

{u'frames': [278.0, 279.0, 280.0, 281.0], u'ID': 3, u'posX': [140.67430647143735, 116.0100804227002, 100.25034175771333, 59.89355756531276], u'posY': [39.36141787911559, 92.24194194246496, 87.3710798883983, 50.782105045050315]}


In [18]:
print(temp['cars'][0]['posX'][200])

836.328871103


In [17]:
print(temp['cars'][0]['posY'][200])

336.168801877


In [33]:
print('Ground truth: {}'.format(gD['cars'][0]['speed']))
print('Optimal_calib_system: {}'.format(temp['cars'][0]['speed']))

Ground truth: 75.9129425052


KeyError: 'speed'

In [21]:
data1 = json.load(open('C:/Users/ADMINS/Desktop/BrnoCompSpeed/code/results/session0_center/system_dubska_bmvc14.json'))
data2 = json.load(open('C:/Users/ADMINS/Desktop/BrnoCompSpeed/code/results/session0_center/system_dubska_optimal_calib.json'))
print(data1['camera_calibration'])

{u'pp': [960.5, 540.5], u'scale': 0.0144311, u'vp1': [144.737, 34.7794], u'vp2': [24380.6, 254.759]}


In [ ]:
# for key, value in data1.iteritems() :
#     print(key)
print(type(data1['cars'][0]['frames']))
print(type(data1['camera_calibration']))
print(data1['camera_calibration'])
print(data2['camera_calibration'])

In [ ]:
import pickle
own_data_link = 'C:/Users/ADMINS/Desktop/result.pkl'
with open(own_data_link, 'rb') as fid:
    own_data = pickle.load(fid)

In [114]:
print(data1['camera_calibration'])

{u'pp': [960.5, 540.5], u'scale': 0.0144311, u'vp1': [144.737, 34.7794], u'vp2': [24380.6, 254.759]}


In [34]:
data = json.load(open('C:/Users/ADMINS/Desktop/speed measure/result.json'))
print(data)

{u'cars': [{u'frames': [278.0, 279.0, 280.0, 281.0], u'ID': 0, u'posX': [140.62665557861328, 113.96309280395508, 98.2859878540039, 59.54088020324707], u'posY': [39.395039558410645, 91.58171463012695, 86.51529312133789, 50.24823760986328]}, {u'frames': [278.0, 279.0, 280.0, 281.0, 282.0, 283.0, 284.0], u'ID': 1, u'posX': [140.6978307198964, 115.03187184670998, 99.45505671400191, 59.52519192049802, 84.49835586547852, 170.06694793701172, 84.33807754516602], u'posY': [39.348509668017975, 91.81019598800471, 86.97434226808384, 50.275805580582656, 122.75128555297852, 406.7292938232422, 132.74312591552734]}, {u'frames': [278.0, 279.0, 280.0, 281.0, 282.0, 283.0, 284.0], u'ID': 2, u'posX': [140.6936955743031, 115.54025363595437, 99.8170248823495, 59.62798589406615, 84.4851125594477, 170.05588641987768, 84.2429866409759], u'posY': [39.36422024368087, 92.1121217866048, 87.12647051805588, 50.44324624435893, 122.33924022541969, 406.7504403925494, 132.71271055772502]}, {u'frames': [278.0, 279.0, 280